name: CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t music-recommender .
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Tag and Push Image
        run: |
          docker tag music-recommender ${{ secrets.DOCKER_USERNAME }}/music-recommender:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/music-recommender:latest          